version: 0.1.{build}
configuration: Release

install:
  - nuget restore

build:
  project: cs-test.sln
  verbosity: minimal

environment:
  COVERALLS_REPO_TOKEN:
    secure: 3EbRXPQkldKUCN544xogYZ7Py3ccW/V6WGqeTY4AtVRqXlZvHRBIv8a7rw07l6o/

after_test:
  - packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" -targetargs:"/noshadow /domain:single cs-test.Test\bin\Release\cs-test.Test.dll" -output:coverage.xml
  - packages\coveralls.net.0.6.0\tools\csmacnz.Coveralls.exe --opencover coverage.xml

artifacts:
  - path: cs-test.UI\bin\Release\*

on_finish:
  - ps: .\cs-test.UI\bin\Release\cs-test.UI.exe
